### ISSUE TITLE
`require 'mongo'` failing

### ISSUE THREAD

**Issue by zmsmith** [edelight/chef-mongodb#10]
I assume this refers to a gem? Tried installing it using the `gem_package` resource, but no luck.

Probably obvious problem, but I don't write much ruby.

**Comment by zmsmith** [comment]
This is on line 153 of mongodb.rb

**Comment by thekorn** [comment]
Hi Zach,
Yes, this indeed refers to a gem. The mongodb cookbook should install this gem while running the mongodb::default recipe

Can you please run 'irb' on the target node and execute    require 'mongo'  . Is this working correctly?

Markus

**Comment by zmsmith** [comment]
It looks like it's more of a chef problem.

When I include the mongos recipe using the `include_recipe` directive in another recipe, the logic around installing the gem doesn't work correctly.

Also, when I just do `gem_package mongo`, the recipe fails, but if I install the gem the way you're doing it, it works.

I'm running into a different problem now the my mongos machines though, which is that a mongod process is being launched and blocking mongos from running because of a port collision.

Have you seen this before?

Thanks

**Comment by thekorn** [comment]
Yes, installing the gem the way I do in the mongodb::default recipe is the one and only (tm) solution. This way it's guaranteed that this gem is installed in a very early stage of a chef run (compile time), the chef wiki has some useful information wrt. this topic [0]

And now to your next question ;) - Yes I've seen this before. The mongodb cookbook currently does not support running multiple mongodb instances (single mongodb, configserver, shardserver, etc.) on one single machine. The reason is that the cookbook configures all mongodb services to run on the same port (see the   node[:mongodb][:port] attribute). And the value of this attribute is global for each node, so you cannot run two instances on the same node.
There is one special case which should be properly handled by the cookbook: the default instance running after package installation. This instance should be shutdown by the recipes.

I hope this explains the problems you are have running the mongodb cookbook, thanks for your feedback.

Markus

[0] http://wiki.opscode.com/display/chef/Evaluate+and+Run+Resources+at+Compile+Time

**Comment by zmsmith** [comment]
It looks like the process is being run on boot without sourcing /etc/deaults/mongos. Then when I try to start mongos through the service command, the ports collide.

I'm not really sure why that is, but I'm going to try making /etc/init.d/mongos a template and scrap the defaults file for now. If it works, I'll shoot you a pull request.

Are you opposed to templating the init.d script rather than overwriting the PID and deamon in defaults?

**Comment by thekorn** [comment]
Sorry Zach, I'm not sure if I got what you mean, but  /etc/init.d/mongos  is already created from the mongodb.init.erb template.
I don't think it makes sense to hardcode the port in the service file itself, setting these values should be done using the files in /etc/default/, IMHO

**Comment by zmsmith** [comment]
Ah, I see you already did this.

I was on an older version of the cookbook, but they had the same version number.
