### ISSUE TITLE
Amazon OpsWorks Setup

### ISSUE THREAD

**Issue by Cyclic** [edelight/chef-mongodb#107]
This is more of a question than an issue. I am happy to provide a wiki page for setting up an AWS OpsWorks layer that others can use to follow if someone here can help me get past this issue and rolling. I created a new, custom layer in OpsWorks, and added this git repo to the custom section; then I added 'mongodb' in the recipe, under the setup section (I also tried using 'mongodb::default'. When I create and start a new instance of amazon linux, x64, mini, in the custom layer, I get the following error at the setup stage of the new instance start:

[Sat, 18 May 2013 01:46:54 +0000] INFO: Executing custom recipe: mongodb
[Sat, 18 May 2013 01:46:54 +0000] DEBUG: Loading Recipe mongodb via include_recipe
[Sat, 18 May 2013 01:46:54 +0000] ERROR: Caught exception during execution of custom recipe: mongodb: ArgumentError - Cannot find a recipe matching default in cookbook mongodb - /opt/aws/opsworks/releases/20130515001926_119/vendor/bundle/ruby/1.8/gems/chef-0.9.15.5/bin/../lib/chef/cookbook_version.rb:462:in `load_recipe'
/opt/aws/opsworks/releases/20130515001926_119/vendor/bundle/ruby/1.8/gems/chef-0.9.15.5/bin/../lib/chef/mixin/language_include_recipe.rb:40:in`include_recipe'

The question is, what should I be using as the recipe name for a single server in the recipe field?
![customlayer](https://f.cloud.github.com/assets/553800/521017/533b1da2-bf5e-11e2-83d1-4ff91cf6d90b.png)

Thanks in advance!

**Comment by Cyclic** [comment]
The directory structure wasn't clear in the documentation. I had to move the entire fork from this repo into a subdirectory named mongodb. Now facing the issue with the package not found error below:

[Sun, 19 May 2013 02:08:04 +0000] DEBUG: mongo-10gen-server: Installed version:  Candidate version: 
[Sun, 19 May 2013 02:08:04 +0000] ERROR: package[mongo-10gen-server](/opt/aws/opsworks/current/site-cookbooks/mongodb/recipes/default.rb:22:in `from_file') had an error:
No version specified, and no candidate version available for mongo-10gen-server

UPDATE:
After adding mongodb::10gen_repo to the setup section of the layer, before the mongodb::default entry, I get another error about the yum_repository method:

[Sun, 19 May 2013 02:48:06 +0000] DEBUG: Found recipe 10gen_repo in cookbook mongodb
[Sun, 19 May 2013 02:48:09 +0000] ERROR: Caught exception during execution of custom recipe: mongodb::10gen_repo: NoMethodError - undefined method `yum_repository' for #<Chef::Recipe:0x7fc08690ff80> - /opt/aws/opsworks/releases/20130515001926_119/vendor/bundle/ruby/1.8/gems/chef-0.9.15.5/bin/../lib/chef/mixin/recipe_definition_dsl_core.rb:56:in`method_missing'
/opt/aws/opsworks/current/site-cookbooks/mongodb/recipes/10gen_repo.rb:43:in `from_file'

**Comment by jeremyolliver** [comment]
Having fiddled a little with OpsWorks before, a few observations about it that may help:
- As you note, it expects a directory structure, this is a hangover from how things used to be done with chef. Effectively it wants a repo the same way that cookbooks used to be managed before being split into the opscode-chef organisation: One repo, with a `cookbooks` directory, containing all cookbooks that you will be loading. This means that any dependent cookbooks (e.g. `apt` or `yum`) would need to be present there as well. (This makes updating any cookbooks a bit of a pain)
- OpsWorks chef also runs on chef 0.9.X if you hadn't noticed yet, which means that some cookbooks may have compatibility issues. I'm not sure if your error `undefined method "yum_repository"` is such an issue. I'd recommend adding the yum recipe to the first item in your run_list as the first thing to try.

**Comment by jamesonjlee** [comment]
for OpsWorks would will need to shim in `apt` and `yum` into your custom cookbooks repo.  There are some patches here and there that would be needed in this recipe because we don't support chef9 (it's lifecycle ended 1 year ago in 3 weeks).

you should see more issues with `platform_family`, where you may need to replace them with `node['platform']`

**Comment by Cyclic** [comment]
Thanks! I had to add the yum repo as Jeremy suggested, and then remove it with another recipe so that the rest of the machine setup would not try to use the 10gen repo. I also ran into the issues that James mentioned, and ended up changing some of the code to work with chef 9. Although it's still not ready for all of the features that the original recipe offers, the version I was working on is still functional for a single server deployment. I went ahead and forked the opsworks repo and added a copy of this recipe with my modifications to it. Amazon sent me a message on the forums and said that they are in the process of upgrading Chef, so we should be able to get this recipe added in its current form soon.

Thanks for the insights!

**Comment by josephholsten** [comment]
@Cyclic is there a particular reason you're using chef 0.9? I do want to make sure things continue to work for reasonably modern versions of in the [test-kitchen branch](https://github.com/edelight/chef-mongodb/pull/115) I'm working on, but I thought I only needed to work with 0.10/10 & 11.

**Comment by jamesonjlee** [comment]
@josephholsten OpsWorks (a chef-solo based configuration management tool on AWS) runs a custom version of chef 0.9.15

**Comment by josephholsten** [comment]
Oh, great. @Cyclic could you point me at the forum post saying amazon is updating chef? Or what the ETA and version they'll be releasing will be?

**Comment by Cyclic** [comment]
@josephholsten Here you go:

Post regarding a more recent version of chef:
https://forums.aws.amazon.com/message.jspa?messageID=453007#453007

A post regarding issues with the current version:
https://forums.aws.amazon.com/message.jspa?messageID=453008#453008

Once their version of Chef is updated, then you should be able to simply push out the inclusion of the yum repo in your docs. In addition, the custom layer UI allows you to specify the EBS Raid 10 or no raid options, but MongoDB suggests that you create a separate volume for journaling, and that the journal volume be hard-linked in the data volume -- something to consider for a patch, which I had incorporated in the version I made a pull request for.

They don't mention a date, but I think it has been added to the priority list; although, more people bugging them is probably just going to bump it up a bit.

**Comment by jtescher** [comment]
OpsWorks now supports Chef 11. Any chance of getting this re-evaluated? http://aws.amazon.com/about-aws/whats-new/2013/07/24/aws-opsworks-supports-chef-custom-ami/

**Comment by josephholsten** [comment]
@jtescher I'll gladly help get it working on chef 11 opsworks, but I don't have a setup of my own. Can you include any errors you're currently seeing?

**Comment by jtescher** [comment]
Sure, looks like it's trying to make an authenticated request when loaded. Could it be related to #56?

DEBUG: Loading Recipe opsworks_stack_state_sync via include_recipe
[2013-08-09T18:53:44+00:00] DEBUG: Found recipe default in cookbook opsworks_stack_state_sync
[2013-08-09T18:53:44+00:00] DEBUG: Loading Recipe opsworks_stack_state_sync::hosts via include_recipe
[2013-08-09T18:53:44+00:00] DEBUG: Found recipe hosts in cookbook opsworks_stack_state_sync
[2013-08-09T18:53:44+00:00] DEBUG: Loading Recipe mongodb via include_recipe
[2013-08-09T18:53:44+00:00] DEBUG: Found recipe default in cookbook mongodb
[2013-08-09T18:53:44+00:00] DEBUG: Loading Recipe mongodb::replicaset via include_recipe
[2013-08-09T18:53:44+00:00] DEBUG: Found recipe replicaset in cookbook mongodb
[2013-08-09T18:53:44+00:00] DEBUG: Loading Recipe mongodb via include_recipe
[2013-08-09T18:53:44+00:00] DEBUG: I am not loading mongodb, because I have already seen it.
[2013-08-09T18:53:44+00:00] DEBUG: Loading Recipe mongodb::default via include_recipe
[2013-08-09T18:53:44+00:00] DEBUG: I am not loading mongodb::default, because I have already seen it.
[2013-08-09T18:53:44+00:00] WARN: Failed to read the private key /etc/chef/client.pem: #<Errno::ENOENT: No such file or directory - /etc/chef/client.pem>
[2013-08-09T18:53:44+00:00] DEBUG: filtered backtrace of compile error: 
[2013-08-09T18:53:44+00:00] DEBUG: filtered backtrace of compile error: 
[2013-08-09T18:53:44+00:00] DEBUG: backtrace entry for compile error: '/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/rest.rb:430:in `load_signing_key''
[2013-08-09T18:53:44+00:00] DEBUG: Line number of compile error: '430'
[2013-08-09T18:53:44+00:00] ERROR: Caught exception while compiling opsworks custom run list: Chef::Exceptions::PrivateKeyMissing - I cannot read /etc/chef/client.pem, which you told me to use to sign requests! - /opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/rest.rb:430:in`load_signing_key'

**Comment by jamesonjlee** [comment]
yep, this looks like chef-search related error (aka, this is chef-solo, so you can't search or authenticate)

**Comment by PratheepV** [comment]
Hi,

I am trying this recipe in Amazon Opswork but getting error Chef::Exceptions::PrivateKeyMissing
Any work around for this?

I got struck..

Thanks,
Pratheepv

**Comment by josephholsten** [comment]
@jtescher ah, well OpsWorks is using chef-solo, so I'm guessing it's blowing up in the replicaset or shard search. #125 adds solo support, but it's rather large and it needs to be broken up a little bit.

**Comment by jamesonjlee** [comment]
@PratheepV the cookbook right now requires a chef server to work with sharding, we are working on figuring out a way around it for chef-solo situation.  I think the current 'best' route is add in solo support that will allow skipping of the search if a list is provided.
