### ISSUE TITLE
Adding first node in replica set

### ISSUE THREAD

**Issue by zmsmith** [edelight/chef-mongodb#14]
If I'm adding the first node of a replica set, isn't the `members` variable being passed into `configure_replicasetconfigure_replicaset` always going to have a length of zero and this check in libraries/mongodb.rb:31 always going to catch?

``` ruby
if members.length == 0
   abort("cannot configure replicaset '#{name}', no member nodes found")
end
```

Seems like I must be overlooking something obvious.

Thanks.

**Comment by thekorn** [comment]
Yeah, it seems you are overlooking something ;)
There is a search in the mongodb_instance definition at line 136 ([0]). The result of this search is used as members parameter of the configure_replicaset method.
So if you have properly set node['mongodb']['cluster_name'] on both nodes to the same value, and both are in the same environment then the length of members should be two, in your case.

[0] https://github.com/edelight/chef-cookbooks/blob/master/mongodb/definitions/mongodb.rb#L136

**Comment by zmsmith** [comment]
Yeah I saw that.

Maybe I'm misunderstanding the workflow. 

I'm trying to add three nodes into a replicaset. It's pretty much the same setup as you've laid out in the wiki.

Once I add other nodes, the search will find them correctly, but when I'm adding the first node into a shard, the search doesn't find anything. 

I believe chef doesn't write back to the server until the run is finished, so on the first run, the search doesn't find the node it's running on. Because this is the first node, it can't find the other potential matching nodes, so the search returns an empty list that is passed into `configure_replicaset` as `members` and has length 0.

Thoughts?

**Comment by thekorn** [comment]
Closed by fa596d6f245afa0dcaf209c5c

We discussed this issue and decided to not abort the configuration in chef-server runs when no members are found. Intead a warning is printed to the logs and the configuration of the replicaset just stops.

Thanks for your input,
Markus

**Comment by zmsmith** [comment]
Great. That's the solution I was using. Glad to be able to get back on trunk. 

Thanks.

**Comment by markbate** [comment]
I'm also hitting this issue in the latest cookbook (v.0.11, installing from 10gen's repo), but am not 100% sure how to get past it.
I get that the Chef run fails because the replica set size is 0, but how do you boot that first node?
I tried doing another run on the node, it still fails. I tried booting a 2nd replica set node, but that fails as the first never completed. I also tried booting a standalone node (mongodb::default) with the cluster_name defined & then booting a replicaset node with the same cluster_name, but that also failed.
Can you please provide info as to how to boot the initial instance there.

Also something that may or may not be related... it seems that the cookbook isn't picking up my node['mongodb']['cluster_name'] attribute. The error message I get always says: "cannot configure replicaset 'rs_default', no member nodes found"
However, if I log the ohai data of the node, I can clearly see the cluster_name defined as an override_attribute.
Any ideas?
