### ISSUE TITLE
Version 0.13.3 syntax error on default and ubuntu, debian is not installing

### ISSUE THREAD

**Issue by carlitux** [edelight/chef-mongodb#154]
https://github.com/edelight/chef-mongodb/blob/0.13.3/recipes/default.rb

```
# configure default instance
mongodb_instance "mongodb" do
  mongodb_instance node['mongodb']['instance_name'] do
  bind_ip node['mongodb']['bind_ip']
  port node['mongodb']['port']
  logpath node['mongodb']['logpath']
  dbpath node['mongodb']['dbpath']
  enable_rest node['mongodb']['enable_rest']
  smallfiles node['mongodb']['smallfiles']
end
```

**Comment by pmcjury** [comment]
+1

Also the source from github and the download from the community site are out of sync. Github is still at 13.2.0

This has a significant effect ( though notthis cookbooks direct fault ) on the graylog2 cook book, because it depends on mongodb >- 13.0.0 so it tried to pull the latest 13.3.0 and is rejected when trying to upload to chef server, because fo the syntax error.

**Comment by jamesonjlee** [comment]
pushed out 0.13.4, pushing up also to the community site
