### ISSUE TITLE
Error while adding a new replicaset member

### ISSUE THREAD

**Issue by tobami** [edelight/chef-mongodb#17]
When configuring a node which is not yet member of a replicaset, different errors can occur.

Depending on whether the primary was configured first or not.

Primary first:
`ERROR: configuring replicaset returned: #<BSON::OrderedHash:0x3f81e4b9a140 {"ok"=>1.0}>`
In this case I _think_ that the operation is successful.

New member first:
`WARN: Could not connect to database: 'localhost:27017'`
and the new member is not added to the primary (possible iptables not yet configured at the primary?)

I think that the code responsible for adding replicaset members should be refactored to take better into account the different situations.

**Comment by danieltahara** [comment]
The issue is that while mongo starts up, it takes a good 2-3 minutes for preallocing and setup to occur (depending on machine).  So by the time the recipe tries to establish a connection, mongo has not yet opened up port 27017 (it's the last step in the setup process).  I have a patch for the init.d script that takes care of this issue.
