### ISSUE TITLE
mongodb.conf.erb template always populated with the default attribute values

### ISSUE THREAD

**Issue by twom** [edelight/chef-mongodb#182]
Hi,

I am currently using the chef script and I need to change the default dbpath and logpath variables. The default values do not work on our VM's since they have not enough diskspace in these folders.

So I basically created a new cookbook where I include the mongodb::10gen_repo and mongodb::default recipe. I also create an attributes/default.rb file where I override the two location values:

```
node.default['mongodb']['dbpath'] = '/disk/mongodb/data/'
node.default['mongodb']['logpath']= '/disk/log/mongodb/'
```

However, the resulting /etc/mongodb.conf file always contains the default values (defined in the mongodb/attributes/default.rb file):

```
# Automatically Generated by Chef, do not edit directly!
#

dbpath = /var/lib/mongodb
fork = true
logappend = true
logpath = /var/log/mongodb/mongodb.log
nojournal = false
port = 27017
rest = false
smallfiles = false
```

In my case this causes the install to not work.

I did some digging around, but could not figure out why the mongodb.conf.erb template does not get the values of my assigned recipe. 

Any tips?

**Comment by twom** [comment]
To work around, I started to specify the values at the role level, which works correctly.

**Comment by jamesonjlee** [comment]
This is probably because those values are deprecated and you are suppose to modify 
`node['mongodb']['dbconfig']['logpath']` and `node['mongodb']['dbconfig']['dbpath']`?

My guess is that also doing `node.default[]` value is not being propagated as well (chef bug?)...

**Comment by mkantor** [comment]
It's an ordering problem. [attributes/dbconfig.rb](https://github.com/edelight/chef-mongodb/blob/master/attributes/dbconfig.rb) sets the `node['mongodb']['config']` attributes (which are what actually get written to the conf file) to the values of the "bare" attributes (e.g. `node['mongodb']['dbpath']`) _before_ your cookbook has a chance to override them. It works from roles because in that case Chef knows about the values before attributes/dbconfig.rb is run.

It'd be awkward to fix this in the cookbook, but this behavior is pretty confusing. Are the "bare" config attributes destined to be removed?

@jamesonjlee I think you meant `node['mongodb']['config']`, not `node['mongodb']['dbconfig']`. Also it looks like there might be [a bug in debian-mongodb.init.erb](https://github.com/edelight/chef-mongodb/blob/63799016fa2614cc7aa5ad19a8e9f986a8211a6f/templates/default/debian-mongodb.init.erb#L130) related to this same confusion, but I don't have time to verify right now.

**Comment by samperman** [comment]
I'm not exactly sure if this is related, but `dbconfig.rb` might be contributing to this problem by using `or` instead of `||`

For example:

``` ruby
default['mongodb']['config']['dbpath'] = node['mongodb']['dbpath'] or "/var/lib/mongodb"
```

should read

``` ruby
default['mongodb']['config']['dbpath'] = node['mongodb']['dbpath'] || "/var/lib/mongodb"
```

**Comment by jspiewak** [comment]
I was blocked for a while on the `or` vs. `||` issue.
Changing to `||` got me past it.
Then I ran into the same issue where the mongodb.conf had only the defaults.
I added

```
"config" : {
  "replSet": "myrs"
}
```

to my role's default attributes and the mongodb.conf now reflects that setting.

Presumably I need to keep the outer replicaset_name attribute for now because mongodb_instance in mongodb.rb still uses it when configuring the replica set.

I then ran into #169 which seems to have deviated from the original problem of not starting with --replSet on the command line to how to get the replica set name into the config.

**Comment by jspiewak** [comment]
My last problem was because something had failed to stop mongod and restart it with the replSet config, so it was in fact running without --replSet enabled. I had to kill -9 it, but re-ran chef-client and it is good now.

**Comment by jamesonjlee** [comment]
ugh, I forget about this in ruby, all the `or` and suppose to be `||` and `and` are suppose to be `&&` for assignments.

**Comment by jamesonjlee** [comment]
ok i fixed the issue in latest commit:?

**Comment by josephholsten** [comment]
@twom can you confirm this is resolved?

**Comment by twom** [comment]
@jamesonjlee  and @josephholsten sorry for my delayed response. 

I have tried a fresh install based on 0.14.6 with the following attributes/default.rb file:

```
default[:mongodb][:dbpath] = "/disk/mongodb/data"
default[:mongodb][:logpath] = "/logs/mongodb"
```

still the mongodb.conf file looks like this:

```
#
# Automatically Generated by Chef, do not edit directly!
#
bind_ip = 0.0.0.0
dbpath = /var/lib/mongodb
fork = true
logappend = true
logpath = /var/log/mongodb/mongodb.log
nojournal = false
port = 27017
rest = false
smallfiles = false
```

When I change the attribute file to 

```
default[:mongodb][:config][:dbpath] = "/disk/mongodb/data"
default[:mongodb][:config][:logpath] = "/logs/mongodb/mongodb.log"
```

everything works. However, I do not see anything wrong with using it this way :)

**Comment by jamesonjlee** [comment]
i added a test for this, seems to work fine..?

**Comment by twom** [comment]
I agree that the test looks fine, however is it representing exactly the case where somebody tries to overwrite an attribute in his/her cookbook attributes/default.rb file?

Also when I set the attributes in the role it works fine. So it looks more like it is related to the order of setting the attributes?

in attributes/dbconfig.rb I see

```
default['mongodb']['config']['dbpath'] = node['mongodb']['dbpath'] || "/var/lib/mongodb"
```

So the default value for config default['mongodb']['config']['dbpath']  is set in the mongo recipe. So how would my cookbook be able to override this setting later, without directly referring to default['mongodb']['config']['dbpath'].

After reading the above comments, that is actually the same suggestion @mkantor made.

So I am wondering if the better solution would not be to change the documentation and just say that overwriting these attributes goes through the default['mongodb']['config'] variable

Thanks for feedback!

**Comment by jamesonjlee** [comment]
ah yes, the documentation should get updated, the intention is that people will always update the `node['mongodb']['config']['dbpath']` variable as `node['mongodb']['dbpath']` variable is being deprecated.

**Comment by twom** [comment]
cool, sounds like we are in agreement :) 
Somebody typically does the documentation updates for this cookbook, or shall I just go ahead?

**Comment by jamesonjlee** [comment]
please do.

**Comment by twom** [comment]
See also #222 and #229

One additional question. I see a lot of references in the code to `node['mongodb']['dbpath']`, `node['mongodb']['logpath']` ... etc. I understand that the goal is to move completely away from these attributes (with the ['config'] level) and there have been a number of issues related to that.

Is there any specific reason these "old" attributes are still used instead of the newer `node['mongodb']['config']['dbpath']`, `node['mongodb']['logpath']`, ...

**Comment by jamesonjlee** [comment]
nope, just backwards compat (which should be done at the attribute level), and old/stale references.

anything related to the db configuration file (or acted on due to) should use the `node['mongodb']['config']...`
