### ISSUE TITLE
server is not running with --replSet

### ISSUE THREAD

**Issue by dgarstang** [edelight/chef-mongodb#296]
I'm trying to configure the shards with this cookbook. I am seeing this:

[2014-05-20T17:08:13+00:00] INFO: Configuring replicaset with members mongo-shard-shard0-rs1, mongo-shard-shard0-rs2
[2014-05-20T17:08:13+00:00] ERROR: Failed to configure replicaset, reason: {"ok"=>0.0, "errmsg"=>"server is not running with --replSet"}

I made sure the mongod process wasn't running before running the chef client. Isn't it chef's job to make sure mongod is running with replSet? Very confused about this.

**Comment by douglaslinsmeyer** [comment]
What did the issue turn out to be?

**Comment by jamesonjlee** [comment]
bad documentation not talking about how to configure things.

**Comment by douglaslinsmeyer** [comment]
I'm running into that same problem. Any chance you could help me out by letting me know your configuration?

**Comment by jamesonjlee** [comment]
@douglaslinsmeyer the recipe uses `node['mongodb']['config']['config_name'] = config_value` to automatically generate the configuration file.

this means if you want to set `replSet` you should do `node['mongodb']['config']['replSet`] = true`, because this the file generated is INI style (and the way mongodb consumes the config file) this should make mongodb configure itself as a replSet.

This allows you to extend the configuration without having to set every variable on the cookbook/template all the time. (or that is the intention)

**Comment by milosgajdos** [comment]
`node['mongodb']['config']['replSet']` allows you to set replica set NAME afaik. It does not ENABLE replica set per say. 

This cookbook massively breaks if you use 10gen 2.6 mongo. It should be mentioned in the docs as well!

**Comment by gwaldo** [comment]
Agreed.  This is not working with 2.6.4

```
node.normal['mongodb']['install_method'] = 'mongodb-org'
node.normal['mongodb']['config']['bind_ip'] = '0.0.0.0'
node.normal['mongodb']['dbconfig_file'] = '/etc/mongod.conf'
node.normal['mongodb']['config']['replSet'] = true
node.normal['mongodb']['is_replicaset'] = true
node.normal['mongodb']['cluster_name'] = 'scribe'
node.normal['mongodb']['replSet'] = 'scribe'
node.normal['mongodb']['is_shard'] = false
include_recipe "mongodb::replicaset"
```

yields:

```
ruby_block[config_replicaset] action create[2014-09-12T13:21:59-04:00] ERROR: Failed to configure replicaset, reason: {"ok"=>0.0, "errmsg"=>"server is not running with --replSet"}
```

**Comment by TalkingQuickly** [comment]
Hey for anyone stuck on this, it's due to some changes in paths and naming (e.g. mongodb v mongod etc) in 2.6.something, not sure exactly which one. Something like this in the node definition should sort it out:

```
"mongodb" : {
  // otherwise we end up writing to /etc/mongodb.conf
  "dbconfig_file": "/etc/mongod.conf",
  // no longer called mongodb in 2.6.4
  "default_init_name" : "mongod"
  "config" :  {
    "replSet" : "yourSetName"
  }
}
```

There's still something not right here as when you re-run a cook, mongo doesn't restart and you have to ssh in and run `sudo service mongod restart` so I'm missing something with init script naming but this gets replication working.

**Comment by TalkingQuickly** [comment]
For anyone finding this result via google, this PR:

https://github.com/edelight/chef-mongodb/pull/262

Contains a more exhaustive list of the attributes to be updated.
