### ISSUE TITLE
/etc/default/mongodb not honored on fresh install

### ISSUE THREAD

**Issue by doxavore** [edelight/chef-mongodb#7]
When running this cookbook against a fresh Ubuntu 10.04 instance, it doesn't seem to pick up the options set in `/etc/default/mongodb` upon reboots. I'm not sure if there's something else this cookbook needs, or perhaps it's a purely Ubuntu issue. I can see the contents of `/etc/default/mongodb` to be as I would expect them to be, but it only starts with the `--config` option set directly in `/etc/init.d/mongodb` (almost like the default file isn't there).

**Comment by tobami** [comment]
For some instance types `/etc/default/mongodb` is ignored, and command line options are used instead, because MongoDB is easier to configure that way.

What recipe are you applying? And how are you using it?

**Comment by doxavore** [comment]
I'm just using the `mongodb::replicaset` recipe on 3 machines, and I'm only configuring `cluster_name` and `shard_name`. (Although I'm not using sharding, the recipe uses `rs_#{shard_name}` for the replicaset name.)

**Comment by tobami** [comment]
For mongodb::replicaset, there is no need to set the shard_name. The replicaset name will be taken from the shard_name just because we need a name for it, so if you don't set it it will just be "default".

The reason we did it this way was to be able to handle all cases (mongodb single instances, replicasets and sharded replicasets), and be able to have diferent MongoDB clusters in the same Chef environment. If, for example, we used cluster_name for replicasets, there would be a problem to use the same definition an library for shards, because each replicaset should have a different name.

In any case, what you want is to be able to set the replicaset name, right? That should be possible.
Can you please explain why you want that?

**Comment by doxavore** [comment]
This appears to be fixed in the latest release - both the replicaset_name option and now restarts of the service are taking my defaults. Thank you!
