### ISSUE TITLE
DAEMON_OPTS in init script overwritten in /etc/defaults/mongodb

### ISSUE THREAD

**Issue by johnoliver** [edelight/chef-mongodb#70]
In the init script you can set the DAEMON_OPTS on line 37 of mongodb.init.erb, however on line 45 "/etc/defaults/mongodb" gets called which is defined from mongodb.default.erb.  This will overwrite DAEMON_OPTS.

I found this behaviour very confusing and may be worth adding a comment that if /etc/defaults/mongodb is present that it will probably overwrite DAEMON_OPTS.

**Comment by jamesonjlee** [comment]
ideally we would move to using the config file.  I think though that using the defaults file does give us a way to include non-standard stuff into the init file (e.g. ulimit).  Not sure how useful that actually is since we are maintaining bunch of init scripts.

Cookbook should(will):
1. use default init scripts shipped with mongodb
2. use /etc/mongodb.conf for variables
3. /etc/sysconfig/mongodb (rhel) or /etc/default/mongodb (debian) to add system setting (ulimit stuff)

depending on feasibility...

**Comment by jamesonjlee** [comment]
and it does~
